import fs from 'node:fs';
import assert from 'node:assert/strict';

const moduleSource = fs.readFileSync(new URL('./src/game-trick-board-experience.js', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('./src/game-trick-board-experience.css', import.meta.url), 'utf8');
const main = fs.readFileSync(new URL('./src/main.jsx', import.meta.url), 'utf8');
const pkg = JSON.parse(fs.readFileSync(new URL('./package.json', import.meta.url), 'utf8'));

assert.match(moduleSource, /data-trick-board-experience/, '中央牌桌增强必须具备幂等标记');
assert.match(moduleSource, /role', 'status'/, '回合状态必须使用状态语义');
assert.match(moduleSource, /aria-live', 'polite'/, '回合状态必须支持礼貌播报');
assert.match(moduleSource, /aria-atomic', 'true'/, '回合状态必须整体播报');
assert.match(moduleSource, /role', 'list'/, '四席行动区必须使用列表语义');
assert.match(moduleSource, /role', 'listitem'/, '单个行动卡必须使用列表项语义');
assert.match(moduleSource, /is-passed/, '必须区分过牌状态');
assert.match(moduleSource, /is-waiting/, '必须区分等待状态');
assert.match(moduleSource, /is-played/, '必须区分已出牌状态');
assert.match(moduleSource, /data-latest-trick-play/, '上一手牌必须有独立状态标记');
assert.match(moduleSource, /is-latest-play/, '上一手牌必须具备明确视觉状态');
assert.match(moduleSource, /is-history-play/, '历史出牌必须降低视觉层级');
assert.match(moduleSource, /上一手牌/, '上一手必须提供可理解的中文读屏说明');
assert.match(moduleSource, /trick-board-latest-summary/, '上一手变化必须提供独立状态摘要');
assert.match(moduleSource, /changedToPlay/, '上一手识别必须基于实际动作变化');
assert.match(moduleSource, /classifySpecialPlay/, '特殊炸弹必须使用独立分类函数');
assert.match(moduleSource, /五十K/, '必须识别同花五十K');
assert.match(moduleSource, /黑四/, '必须识别黑四炸弹');
assert.match(moduleSource, /红四/, '必须识别红四炸弹');
assert.match(moduleSource, /八张/, '必须识别八张同点炸弹');
assert.match(moduleSource, /四王/, '必须识别四王炸弹');
assert.match(moduleSource, /cardCountValue = String\(cardCount\)/, '行动卡必须记录实际牌张数');
assert.match(moduleSource, /specialValue = specialPlay \|\| 'normal'/, '行动卡必须记录特殊牌型');
assert.match(moduleSource, /共\$\{cardCount\}张牌/, '读屏说明必须包含实际牌张数');
assert.match(moduleSource, /badge\.textContent !== text|node\.textContent !== text/, '上一手文字必须幂等更新');
assert.match(moduleSource, /if \(!badge\)/, '上一手徽标只能在缺失时创建');
assert.match(moduleSource, /if \(badge\) badge\.remove\(\)/, '非上一手状态只在存在徽标时删除');
assert.doesNotMatch(moduleSource, /removeLatestBadge\(cell\)/, '不得每次扫描都先删除上一手徽标');
assert.doesNotMatch(moduleSource, /summary\.textContent\s*=/, '不得每次扫描都无条件重写上一手摘要');
assert.doesNotMatch(moduleSource, /setInterval\s*\(/, '中央牌桌增强不得使用持续轮询');

assert.match(css, /grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/, '行动记录必须使用稳定两列布局');
assert.match(css, /min-height:\s*78px/, '正常行动卡必须保留可读高度');
assert.match(css, /\.trick-action-card\.is-latest-play/, '上一手牌必须有高层级样式');
assert.match(css, /\.trick-action-card\.is-history-play/, '历史出牌必须有降层级样式');
assert.match(css, /\.trick-action-card__latest-badge/, '上一手牌必须显示文字标记');
assert.match(css, /min-height:\s*22px/, '上一手标记必须保留可读高度');
assert.match(css, /data-card-count="8"/, '八张牌必须具备独立压缩规则');
assert.match(css, /--trick-card-overlap:\s*-16px/, '桌面八张牌必须使用可控重叠');
assert.match(css, /--mini-card-w:\s*32px/, '手机牌面必须保持可读宽度');
assert.match(css, /--mini-rank-font:\s*11px/, '手机牌面点数不得过小');
assert.match(css, /\.trick-action-card\.is-fifty-k/, '五十K必须有独立视觉状态');
assert.match(css, /\.trick-action-card\.is-red-four/, '红四必须有独立视觉状态');
assert.match(css, /\.trick-action-card\.is-black-four/, '黑四必须有独立视觉状态');
assert.match(css, /\.trick-action-card\.is-same-eight/, '八张炸弹必须有独立视觉状态');
assert.match(css, /\.trick-action-card\.is-four-jokers/, '四王必须有独立视觉状态');
assert.match(css, /@media \(max-width: 520px\)/, '必须覆盖手机竖屏');
assert.match(css, /@media \(max-height: 430px\) and \(orientation: landscape\)/, '必须覆盖低高度横屏');
assert.match(css, /@media \(prefers-contrast: more\)/, '必须支持高对比度');
assert.match(css, /@media \(prefers-reduced-motion: reduce\)/, '必须支持减少动画');
assert.match(css, /backdrop-filter:\s*none/, '中央牌桌不得恢复玻璃模糊');
assert.doesNotMatch(css, /#7c3aed|#6366f1|#8b5cf6/i, '中央牌桌不得引入蓝紫荧光主题');

assert.match(main, /installGameTrickBoardExperience/, '中央牌桌增强必须接入正式入口');
assert.match(main, /game-trick-board-experience\.css/, '中央牌桌样式必须接入正式入口');
assert.ok(pkg.scripts.test.includes('game-trick-board-experience.test.js'), '中央牌桌测试必须进入完整测试链');

console.log('game trick board experience tests passed');
