import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import RulesHelpLauncher from './components/RulesHelpLauncher';
import { installGameTableHeaderEnhancer } from './game-table-header';
import { installHandInteractionEnhancer } from './hand-interaction-enhancer';
import { installGameActionGuard } from './game-action-guard';
import { installGameActionFeedback } from './game-action-feedback';
import { installUiFeedbackGovernor } from './ui-feedback-governor.js';
import { installLobbyEntryFeedback } from './lobby-entry-feedback.js';
import './index.css';
import './ui-responsive.css';
import './ui-polish.css';
import './waiting-room.css';
import './game-table-responsive.css';
import './game-table-header.css';
import './hand-interaction.css';
import './game-action-feedback.css';
import './rules-help.css';
import './compact-game-controls.css';
import './ui-design-system.css';
import './lobby-entry.css';
import './lobby-entry-feedback.css';

ReactDOM.createRoot(document.getElementById('root')).render(<><App /><RulesHelpLauncher /></>);
installGameTableHeaderEnhancer();
installHandInteractionEnhancer();
installGameActionGuard();
installGameActionFeedback();
installUiFeedbackGovernor();
installLobbyEntryFeedback();
